### PR TITLE
License Named Instances

### PR DESCRIPTION
**Pull request by duracelltomi**
Introduced the concept of license instance for a licence key to handle named instances of a license like email addresses, hostnames, computer names, etc.

### CODE REVIEW

**Comment by drazenbebic** [comment]
Hello @duracelltomi 

After some changes to the plugin, your PR has some conflicts. Could you fix those please?

**Comment by duracelltomi** [comment]
I am trying but I have to admit I am not a hard core Git user, perhaps you can help me.

The change that stops GitHub to allow an automatic merge is that you moved the functions folder out of includes. I've added this move to my fork as well but GitHub still tells me to resolve conflicts manually I just do not know what conflicts they would like me to resolve:
https://github.com/duracelltomi/license-manager-for-woocommerce/pull/2

**Comment by drazenbebic** [comment]
@duracelltomi

You can just click here on "Resolve conflicts" and edit the two files which have merge conflicts.

**Comment by duracelltomi** [comment]
oh, sorry, done :-)

**Comment by drazenbebic** [comment]
@duracelltomi 

Great! Thanks a lot!

I have read the initial description of what this PR is supposed to do, but I'm not sure I fully understand. Could you provide some additional information before I take a look at this?

**Comment by duracelltomi** [comment]
Use case #1 - SaaS service with some sort of remotely running app (3rd party paid extension to any software or a desktop native app)

Let's suppose a client buys a licence key that can be activated 5 times

Each time, a specific user is using the key.
User starts the app, app is checking the licence key given before but it can only see that the key has been activated 2 times, it can not see whether this user has ever activated before?

Also, license owner can not see who is using the key, just that it was activated 2 times from some source.

Use case #2 - WordPress paid plugin.
User buys a licence key for 5 sites. When the key is activated on one site, the counter increments, but next time, the paid plugin tries to check whether the licence key is valid, it can only see that the key has been activated 2 times but can not see whether any of those activations was initiated from this site or other sites.

With named instances, one can store an ID and next to the activation state, they can also check whether that user or site was any of the activator before.

**Comment by otakupahp** [comment]
I created and SDK to put inside a WP plugin, any improvement to it will be greatly appreciated https://github.com/otakupahp/sdk-license-manager-for-woocommerce

**Comment by gomonkey** [comment]
Hello guys, what about this release?

**Comment by duracelltomi** [comment]
I am sorry guys but I do not have time currently to update the PR to match the latest version of the plugin. I was hoping it will be merged into the version which was live while I was creating the changes.

The basic concept behind my PR was to clone the framework behind the License object and make it a subtable to the Licenses. I created a new admin page and all the API endpoints but since things changed a lot since my PR, I guess most if the code needs to be rewritten from scratch.

**Comment by gomonkey** [comment]
I did it in 10 minutes.

I added in SQL lmfwc_licenses table a column called site VARCHAR(255)

inside **activateLicense** method  (includes\api\v2\Licenses.php) I added the following code:

`$site = sanitize_text_field($request->get_param('site'));`

and then, always in the same method, I am passing variable to update method

```
$updatedLicense = LicenseResourceRepository::instance()->update(
                $license->getId(),
                array(
                    'site' => $site,
                    'times_activated' => $timesActivatedNew
                )
            );
```

inside construct in includes\repositories\resources\Licence.php I added in mapping the new variable

```
$this->mapping    = array(
            'order_id'            => ColumnTypeEnum::BIGINT,
            'product_id'          => ColumnTypeEnum::BIGINT,
            'user_id'             => ColumnTypeEnum::BIGINT,
            'license_key'         => ColumnTypeEnum::LONGTEXT,
            'hash'                => ColumnTypeEnum::LONGTEXT,
            'site'                => ColumnTypeEnum::LONGTEXT,
```

Now I can call API in this way

`wp-json/lmfwc/v2/licenses/activate/ECdZcV-TB60NW-8FMNX1-Fq9ATk?site=google.com`

And it's saved in the database.
Now with the same logic, it is possible to add more parameters

**Comment by gomonkey** [comment]
the above code has been removed

all code inside includes\api\v2\Licenses.php
This is what I did:

`use LicenseManagerForWooCommerce\Repositories\Resources\LicenseMeta as LicenseMetaResourceRepository;`

inside activateLicense method I added the following code:

```
// Get parameter
$site = sanitize_text_field($request->get_param('site'));

// Before the return statment
try {
   LicenseMetaResourceRepository::instance()->insert(
      array(
            'license_id' => $licenseData["id"],
            'meta_key'   => "website",
            'meta_value' => maybe_serialize($site)
         )
      );
} catch (Exception $e) {
   return new WP_Error(
      'lmfwc_rest_data_error',
      $e->getMessage(),
      array('status' => 404)
   );
}
return $this->response(true, $licenseData, 200, 'v2/licenses/activate/{license_key}');
```
Now is save in lmfwc_licenses_meta table.
If you need to save more parameters, it is possible to use a loop

**Comment by drazenbebic** [comment]
Sorry everyone, this feature has deviated too much from the develop branch and is not going to sit well with the future updates I have planned for the plugin. However, the plugin will provide similar functionality in one of the future updates.

**Pull request closed without merging**
