### PR TITLE
Refactoring lmfwc_duplicate

### PR DESCRIPTION
**Pull request by g4m3r0**

### CODE REVIEW

**Comment by otakupahp** [comment]
The modification does not improve the code, in fact it degrades it.

It is better to have just one return instead of many of them. Many returns make the code more difficult to mantain

**Comment by g4m3r0** [comment]
I tend toward leaving the function after everything is complete to have less overhead as well as more fail safety.
It also makes the code more understandable, you can clearly see the "raw" output of the function.
Here is a discussion about it https://stackoverflow.com/questions/30256157/best-practice-for-returning-in-php-function-method .

But 1=1 statements in SQL query shouldn't be include in productive code, that's for sure.

**Comment by drazenbebic** [comment]
Hello @g4m3r0 

I can understand the early exit paradigm, however I personally prefer to have a single exit point at the end of a function. The link you provided also makes it clear that this is largely a matter of opinion. Since there is no benefit to it, I think that this part should remain as it is. 

However, could you please explain why 1=1 SQL statements should not be included in productive code?

**Comment by g4m3r0** [comment]
I just follow simple clean code principles (KISS,DRY,YAGNI).
If you don't need the true statement (no dynamically built query), why should you keep it?

However maybe you are doing it differently and using other clean code principles in high-level languages.
Sadly ReSharper does not support PHP.

**Comment by drazenbebic** [comment]
Will not be merged, I think this is more a matter of opinion than anything else.

**Pull request closed without merging**
