### PR TITLE
optional argument on activate/deactivate entpoint

### PR DESCRIPTION
**Pull request by tony-defa**
Hi Drazan,

I've added some optional parameters to the activate and deactivate endpoints. This can be used to specify the amount of activations or deactivations. I've limited the count to a max of 99 for now. We could make it so that the is unlimited. What do you think?
The general settings page has been updated accordingly. 

The branch has been tested with all possible combinations and it works fine.

### CODE REVIEW

**Comment by drazenbebic** [comment]
@tony-defa 

I think that limiting it to 99 is not needed, limiting the parameter should be up to the developer who is doing the integration of the API.

Have you tested if this breaks existing functionality? What I mean: If I omit the activations/deactivations parameters, does the REST API still activate and deactivate by 1? The code seems to suggest so, but it would still need to be tested, so that existing API integrations don't break.

**Comment by tony-defa** [comment]
@drazenbebic: I can change it so that there is no upper limit.

the '/activationCount' addition is optional and it does not break the existing functionality

**Comment by drazenbebic** [comment]
@tony-defa Yes, please 👍 

I'll double check the rest and then merge the branch when the limit is removed.

**Comment by tony-defa** [comment]
OK Thanks. I'll do the change later today ;)

**Comment by tony-defa** [comment]
@drazenbebic 

The limit has been removed

**Comment by tony-defa** [comment]
Hi @drazenbebic 

I've merged the changes from PR #139.

**Comment by drazenbebic** [comment]
@tony-defa 

The implementation is solid, good work there. 

However, is there a use-case for this? Do you use the feature to activate a license key more than once?

**Comment by tony-defa** [comment]
Hi @drazenbebic 

We use this as a "payment" system so that we can make a certain amount of activations (credits in our case) depending on service usage. 

Therefore the customer buys a credits package (license) and can make use of our services.

**Comment by drazenbebic** [comment]
@tony-defa 

Sorry but I don't see this as part of the plugin. It's kind of out of scope, and you're using it as a workaround for a different functionality.

**Pull request closed without merging**
